version: 0

provider: gemini
timeout: 30000

gemini:
  key: YOUR_GEMINI_API_KEY
  model: gemini-2.5-flash-preview-05-20
  temperature: 0
  top_p: 0.95
  top_k: 64
  max_output_tokens: 8192
  thinking_budget: 0

prompt:
  summarize: Summarize the following text.

  explain: Explain the following concept.

  french: Translate the following text to French.

  commit: |
    Write a conventional commit message in the following form.

    type(optional scope): description

    [optional body]

    [optional footer(s)]

    Use type fix, feat, chore, ci, docs, refactor, perf, test where appropriate.
    Description start lowercase, imperative style.
    Body complete sentences, proper case, concise, imperative style.
