version: 0

provider: gemini
timeout: 30000

gemini:
  key: YOUR_GEMINI_API_KEY
  model: gemini-2.5-flash-preview-04-17
  temperature: 0
  top_p: 0.95
  top_k: 40
  max_output_tokens: 8192
  thinking_budget: 0

prompt:
  summarize: Summarize the following text.

  explain: Explain the following concept.

  french: Translate the following text to French.

  commit: |
    Write a conventional commit message in the following form.

    <type>[optional scope]: <description>

    [optional body]

    [optional footer(s)]

    Description lowercase, imperative style.
    Body and footer proper sentences, proper case, concise, imperative style.
    Use types fix, feat, chore, ci, docs, refactor, perf, test where appropriate.
